[source::XmlWinEventLog:Security]
EVAL-NewProcessIdDecimal = case(EventCode==4688, tonumber(NewProcessId,16))
EVAL-ProcessIdDecimal =  tonumber(ProcessId,16)
EVAL-TargetProcessIdDecimal = case(EventCode==4696,tonumber(TargetProcessId,16))


#Kerberos lookups
LOOKUP-PreAuthEncryptionType = kerberos_encryption_type code AS PreAuthEncryptionType OUTPUTNEW value AS PreAuthEncryptionTypeString 
LOOKUP-SessionKeyEncryptionType = kerberos_encryption_type code AS SessionKeyEncryptionType OUTPUTNEW value AS SessionKeyEncryptionTypeString 
LOOKUP-TicketEncryptionType = kerberos_encryption_type code AS TicketEncryptionType OUTPUTNEW value AS TicketEncryptionTypeString 
LOOKUP-PreAuthType = kerberos_preauth_types code AS PreAuthType OUTPUTNEW value AS PreAuthTypeString, description AS PreAuthTypeDescription
#Percentage lookups
LOOKUP-TokenElevationType = windows_codes code AS TokenElevationType OUTPUTNEW value AS TokenElevationTypeString 
LOOKUP-ElevatedToken = windows_codes code AS ElevatedToken OUTPUTNEW value AS ElevatedTokenString 
LOOKUP-ImpersonationLevel = windows_codes code AS ImpersonationLevel OUTPUTNEW value AS ImpersonationLevelString 
LOOKUP-VirtualAccount= windows_codes code AS VirtualAccount OUTPUTNEW value AS VirtualAccountString 
LOOKUP-LogonType = windows_logon code AS LogonType OUTPUTNEW value AS LogonTypeString 
LOOKUP-AccessList = windows_code code AS AccessList OUTPUTNEW value AS AccessListString 	
LOOKUP-AccessMask = windows_code code AS AccessMask OUTPUTNEW value AS AccessMaskString 	
LOOKUP-AuditPolicyChanges = windows_code code AS AuditPolicyChanges OUTPUTNEW value AS AuditPolicyChangesString 	
LOOKUP-DSType = windows_code code AS DSType OUTPUTNEW value AS DSTypeString 	
LOOKUP-DisplayName = windows_code code AS DisplayName OUTPUTNEW value AS DisplayNameString 	
LOOKUP-FailureReason = windows_code code AS FailureReason OUTPUTNEW value AS FailureReasonString 	
LOOKUP-HypervisorDebug = windows_code code AS HypervisorDebug OUTPUTNEW value AS HypervisorDebugString 	
LOOKUP-LogonHours = windows_code code AS LogonHours OUTPUTNEW value AS LogonHoursString 	
LOOKUP-Operation = windows_code code AS Operation OUTPUTNEW value AS OperationString 	
LOOKUP-OperationType = windows_code code AS OperationType OUTPUTNEW value AS OperationTypeString 	
LOOKUP-PasswordLastSet = windows_code code AS PasswordLastSet OUTPUTNEW value AS PasswordLastSetString 	
LOOKUP-ReadOperation = windows_code code AS ReadOperation OUTPUTNEW value AS ReadOperationString 	
LOOKUP-TreeDelete = windows_code code AS TreeDelete OUTPUTNEW value AS TreeDeleteString 	
