[windows_codes]
filename = windows_codes.csv

[windows_logon]
filename = windows_logon.csv

[kerberos_encryption_type]
filename = kerberos_encryption_type.csv

[kerberos_preauth_types]
filename = kerberos_preauth_types.csv

